
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-iqbalkhan.rhcloud.com:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: openshift
  jpa:
    generate-ddl: true
    show_sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    initialize: false
    testWhileIdl: true
    validationQuery: SELECT 1
security.ignored: /resources/**
eureka:
  instance:
    # prefer-ip-address: true
    # non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-uncrated-doper.cfapps.io/eureka/
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: dev
  jpa:
    generate-ddl: true
    show_sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    initialize: false
    testWhileIdl: true
    validationQuery: SELECT 1
security.ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    # non-secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: cloud
  jpa:
    generate-ddl: true
    show_sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    initialize: false
    testWhileIdl: true
    validationQuery: SELECT 1
security.ignored: /resources/**
eureka:
  instance:
    # prefer-ip-address: true
    # non-secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-uncrated-doper.cfapps.io/eureka/
